// <auto-generated />
using System;
using BDA.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BDA.Migrations
{
    [DbContext(typeof(BdaDBContext))]
    [Migration("20200529043916_ChangePostingDateFromStringToDate")]
    partial class ChangePostingDateFromStringToDate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BDA.Entities.AccountingTable", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("Amount");

                    b.Property<string>("CONW");

                    b.Property<string>("CONWNo");

                    b.Property<string>("CostObject");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Currency");

                    b.Property<string>("DrCr");

                    b.Property<string>("GLAccount");

                    b.Property<bool>("IsActive");

                    b.Property<string>("TaxAmount");

                    b.Property<string>("TaxCode");

                    b.Property<DateTime>("UpdatedOn");

                    b.Property<Guid>("WangHangusId");

                    b.HasKey("Id");

                    b.HasIndex("WangHangusId");

                    b.ToTable("AccountingTable");
                });

            modelBuilder.Entity("BDA.Entities.Attachment", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("FileExtension");

                    b.Property<string>("FileId");

                    b.Property<string>("FileName");

                    b.Property<string>("FileSubType");

                    b.Property<string>("FileType");

                    b.Property<bool>("IsActive");

                    b.Property<Guid>("ParentId");

                    b.Property<string>("Title");

                    b.Property<DateTime>("UpdatedOn");

                    b.HasKey("Id");

                    b.ToTable("Attachment");
                });

            modelBuilder.Entity("BDA.Entities.BankDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccountNo1");

                    b.Property<string>("AccountNo2");

                    b.Property<string>("AccountNo3");

                    b.Property<string>("AddressLine1");

                    b.Property<string>("AddressLine2");

                    b.Property<string>("BankName");

                    b.Property<string>("BankPIC");

                    b.Property<string>("BankPICPosition");

                    b.Property<string>("ChargeAccountNo");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Email");

                    b.Property<string>("State");

                    b.Property<string>("Street");

                    b.Property<string>("Type");

                    b.Property<DateTime>("UpdatedOn");

                    b.Property<bool>("isActive");

                    b.HasKey("Id");

                    b.ToTable("BankDetails");
                });

            modelBuilder.Entity("BDA.Entities.BankDraft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("ApprovedOn");

                    b.Property<string>("ApproverComment");

                    b.Property<string>("ApproverId");

                    b.Property<string>("BankDrafNoIssued");

                    b.Property<decimal?>("BankDraftAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("BankDraftDate");

                    b.Property<DateTime?>("CompletedOn");

                    b.Property<string>("CoverMemoRefNo");

                    b.Property<string>("CreatedById");

                    b.Property<string>("CreatedByName");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime?>("DraftedOn");

                    b.Property<string>("FinalApplication");

                    b.Property<string>("InstructionLetterRefNo");

                    b.Property<string>("PostageNo");

                    b.Property<string>("ProjectNo");

                    b.Property<string>("ReceiptNo");

                    b.Property<DateTime?>("ReceiveBankDraftDate");

                    b.Property<string>("ReceiverContactNo");

                    b.Property<string>("RefNo");

                    b.Property<string>("RequesterComment");

                    b.Property<string>("RequesterId");

                    b.Property<string>("RequesterSubmissionComment");

                    b.Property<string>("SendMethod");

                    b.Property<string>("Status");

                    b.Property<DateTime?>("SubmittedOn");

                    b.Property<string>("TGBSAcceptanceId");

                    b.Property<string>("TGBSAcceptedComment");

                    b.Property<DateTime?>("TGBSAcceptedOn");

                    b.Property<DateTime?>("TGBSIssuedOn");

                    b.Property<string>("TGBSIssuerId");

                    b.Property<DateTime?>("TGBSProcessedOn");

                    b.Property<string>("TGBSProcesserId");

                    b.Property<string>("Type");

                    b.Property<DateTime>("UpdatedOn");

                    b.Property<DateTime?>("VerifiedOn");

                    b.Property<string>("VerifierComment");

                    b.Property<string>("VerifierId");

                    b.Property<DateTime?>("WithdrewOn");

                    b.Property<bool>("isActive");

                    b.HasKey("Id");

                    b.HasIndex("ApproverId");

                    b.HasIndex("RequesterId");

                    b.HasIndex("TGBSAcceptanceId");

                    b.HasIndex("TGBSIssuerId");

                    b.HasIndex("TGBSProcesserId");

                    b.HasIndex("VerifierId");

                    b.ToTable("BankDraft");
                });

            modelBuilder.Entity("BDA.Entities.BankDraftAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ActionRole");

                    b.Property<string>("ActionType");

                    b.Property<string>("ApplicationType");

                    b.Property<string>("ById");

                    b.Property<string>("Comment");

                    b.Property<DateTime>("On");

                    b.Property<Guid>("ParentId");

                    b.HasKey("Id");

                    b.HasIndex("ById");

                    b.ToTable("BankDraftAction");
                });

            modelBuilder.Entity("BDA.Entities.BusinessArea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<Guid>("StateId");

                    b.Property<string>("Zone");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("BusinessArea");
                });

            modelBuilder.Entity("BDA.Entities.Cancellation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("ApprovedOn");

                    b.Property<string>("ApproverComment");

                    b.Property<string>("ApproverId");

                    b.Property<string>("BA");

                    b.Property<decimal?>("BDAmount");

                    b.Property<string>("BDNo");

                    b.Property<string>("BDRequesterName");

                    b.Property<Guid>("BankDraftId");

                    b.Property<string>("BankProcessType");

                    b.Property<string>("CoCode");

                    b.Property<DateTime?>("CompletedOn");

                    b.Property<string>("CreatedById");

                    b.Property<string>("CreatedByName");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime?>("DraftedOn");

                    b.Property<string>("ERMSDocNo");

                    b.Property<string>("InstructionLetterRefNo");

                    b.Property<string>("NameOnBD");

                    b.Property<string>("OthersRemark");

                    b.Property<string>("ProjectNo");

                    b.Property<string>("ReasonCancel");

                    b.Property<DateTime?>("ReceivedDate");

                    b.Property<DateTime?>("ReceivedOn");

                    b.Property<string>("ReconReceiverId");

                    b.Property<string>("RefNo");

                    b.Property<string>("RequesterId");

                    b.Property<string>("Status");

                    b.Property<DateTime?>("SubmittedOn");

                    b.Property<string>("TGBSAcceptanceId");

                    b.Property<string>("TGBSAcceptedComment");

                    b.Property<DateTime?>("TGBSAcceptedOn");

                    b.Property<string>("TGBSConfirmationComment");

                    b.Property<DateTime?>("TGBSProcessedOn");

                    b.Property<string>("TGBSProcesserId");

                    b.Property<string>("TGBSReceiverId");

                    b.Property<string>("TGBSValidatorId");

                    b.Property<DateTime>("UpdatedOn");

                    b.Property<DateTime?>("WithdrewOn");

                    b.Property<bool>("isActive");

                    b.HasKey("Id");

                    b.HasIndex("ApproverId");

                    b.HasIndex("BankDraftId");

                    b.HasIndex("ReconReceiverId");

                    b.HasIndex("RequesterId");

                    b.HasIndex("TGBSAcceptanceId");

                    b.HasIndex("TGBSProcesserId");

                    b.ToTable("Cancellation");
                });

            modelBuilder.Entity("BDA.Entities.CancellationReason", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("CancellationReason");
                });

            modelBuilder.Entity("BDA.Entities.CompanyCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("CompanyCode");
                });

            modelBuilder.Entity("BDA.Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("BDA.Entities.Division", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<int>("LOAType");

                    b.Property<string>("Name");

                    b.Property<DateTime>("UpdatedOn");

                    b.Property<bool>("isActive");

                    b.HasKey("Id");

                    b.ToTable("Division");
                });

            modelBuilder.Entity("BDA.Entities.ERMSQueues", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<DateTime>("ActionDate");

                    b.Property<Guid?>("BankDrafIdId");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Function");

                    b.Property<bool>("IsActive");

                    b.Property<string>("RefNo");

                    b.Property<string>("Status");

                    b.Property<DateTime>("UpdatedOn");

                    b.HasKey("Id");

                    b.HasIndex("BankDrafIdId");

                    b.ToTable("ERMSQueues");
                });

            modelBuilder.Entity("BDA.Entities.EmailQueues", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("Attachments");

                    b.Property<string>("Content");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<bool>("IsActive");

                    b.Property<DateTime>("ObjectId");

                    b.Property<DateTime>("ProcessedOn");

                    b.Property<DateTime>("ScheduledOn");

                    b.Property<DateTime>("SentOn");

                    b.Property<string>("Subject");

                    b.Property<string>("ToAddress");

                    b.Property<string>("ToName");

                    b.Property<DateTime>("UpdatedOn");

                    b.HasKey("Id");

                    b.ToTable("EmailQueues");
                });

            modelBuilder.Entity("BDA.Entities.EmailTemplates", b =>
                {
                    b.Property<string>("Id");

                    b.Property<string>("Body");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Subject");

                    b.Property<DateTime>("UpdatedOn");

                    b.HasKey("Id");

                    b.ToTable("EmailTemplates");
                });

            modelBuilder.Entity("BDA.Entities.Function", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<Guid>("DivisionId");

                    b.Property<string>("Name");

                    b.Property<DateTime>("UpdatedOn");

                    b.Property<bool>("isActive");

                    b.HasKey("Id");

                    b.HasIndex("DivisionId");

                    b.ToTable("Function");
                });

            modelBuilder.Entity("BDA.Entities.InstructionLetter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AddressLine1");

                    b.Property<string>("AddressLine2");

                    b.Property<string>("AddressLine3");

                    b.Property<string>("ApplicationType");

                    b.Property<string>("BankAccount");

                    b.Property<string>("BankName");

                    b.Property<string>("BankPIC");

                    b.Property<string>("ChargedBankAccount");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("InstructionLetterEmail");

                    b.Property<DateTime?>("LetterDate");

                    b.Property<string>("LetterRefNo");

                    b.Property<string>("ProcessingType");

                    b.Property<string>("ReferenceNo");

                    b.Property<string>("Remarks");

                    b.Property<string>("RinggitText");

                    b.Property<string>("State");

                    b.Property<string>("Status");

                    b.Property<DateTime>("UpdatedOn");

                    b.Property<DateTime?>("ValueDate");

                    b.Property<bool>("isActive");

                    b.HasKey("Id");

                    b.ToTable("InstructionLetter");
                });

            modelBuilder.Entity("BDA.Entities.InstructionLetterAttachment", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<Guid?>("AttachmentId");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<Guid>("InstructionLetterId");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Type");

                    b.Property<DateTime>("UpdatedOn");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentId");

                    b.HasIndex("InstructionLetterId");

                    b.ToTable("InstructionLetterAttachment");
                });

            modelBuilder.Entity("BDA.Entities.JkrType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("JkrType");
                });

            modelBuilder.Entity("BDA.Entities.Lost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("ApprovedOn");

                    b.Property<string>("ApproverComment");

                    b.Property<string>("ApproverId");

                    b.Property<string>("BA");

                    b.Property<decimal?>("BDAmount");

                    b.Property<string>("BDNo");

                    b.Property<string>("BDRequesterName");

                    b.Property<Guid>("BankDraftId");

                    b.Property<string>("CoCode");

                    b.Property<DateTime?>("CompletedOn");

                    b.Property<string>("CreatedById");

                    b.Property<string>("CreatedByName");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime?>("DraftedOn");

                    b.Property<string>("ERMSDocNo");

                    b.Property<string>("InstructionLetterRefNo");

                    b.Property<string>("Justification");

                    b.Property<string>("NameOnBD");

                    b.Property<string>("ProjectNo");

                    b.Property<DateTime?>("ReceivedDate");

                    b.Property<DateTime?>("ReceivedOn");

                    b.Property<string>("ReconReceiverId");

                    b.Property<string>("RefNo");

                    b.Property<string>("RequesterId");

                    b.Property<string>("Status");

                    b.Property<DateTime?>("SubmittedOn");

                    b.Property<string>("TGBSAcceptanceId");

                    b.Property<string>("TGBSAcceptedComment");

                    b.Property<DateTime?>("TGBSAcceptedOn");

                    b.Property<string>("TGBSConfirmationComment");

                    b.Property<DateTime?>("TGBSProcessedOn");

                    b.Property<string>("TGBSProcesserId");

                    b.Property<string>("TGBSReceiverId");

                    b.Property<string>("TGBSValidatorId");

                    b.Property<DateTime>("UpdatedOn");

                    b.Property<DateTime?>("WithdrewOn");

                    b.Property<bool>("isActive");

                    b.HasKey("Id");

                    b.HasIndex("ApproverId");

                    b.HasIndex("BankDraftId");

                    b.HasIndex("ReconReceiverId");

                    b.HasIndex("RequesterId");

                    b.HasIndex("TGBSAcceptanceId");

                    b.HasIndex("TGBSProcesserId");

                    b.ToTable("Lost");
                });

            modelBuilder.Entity("BDA.Entities.Memo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApplicationType");

                    b.Property<string>("Approver");

                    b.Property<string>("ApproverAddress");

                    b.Property<string>("CoverRefNo");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime?>("Date");

                    b.Property<string>("IssuedBDReceiverContactNo");

                    b.Property<string>("Line1");

                    b.Property<string>("Line2");

                    b.Property<string>("Line3");

                    b.Property<string>("Line4");

                    b.Property<string>("Line5");

                    b.Property<string>("LineETC");

                    b.Property<string>("ReferenceNo");

                    b.Property<string>("RequestorAddress");

                    b.Property<string>("SendingMethod");

                    b.Property<string>("Signiture");

                    b.Property<string>("Status");

                    b.Property<string>("UP");

                    b.Property<DateTime>("UpdatedOn");

                    b.Property<bool>("isActive");

                    b.HasKey("Id");

                    b.ToTable("Memo");
                });

            modelBuilder.Entity("BDA.Entities.MemoAttachment", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<Guid?>("AttachmentId");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<bool>("IsActive");

                    b.Property<Guid>("MemoId");

                    b.Property<string>("Type");

                    b.Property<DateTime>("UpdatedOn");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentId");

                    b.HasIndex("MemoId");

                    b.ToTable("MemoAttachment");
                });

            modelBuilder.Entity("BDA.Entities.MonthlyAmount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<int>("Month");

                    b.Property<DateTime>("UpdatedOn");

                    b.Property<int>("Year");

                    b.Property<decimal?>("diffAmount");

                    b.Property<decimal?>("diffAmountRecovery");

                    b.Property<bool>("isActive");

                    b.Property<decimal?>("percentageAmount");

                    b.Property<decimal?>("percentageAmountRecovery");

                    b.Property<decimal?>("sumAmount");

                    b.Property<decimal?>("sumRecovery");

                    b.HasKey("Id");

                    b.ToTable("MonthlyAmount");
                });

            modelBuilder.Entity("BDA.Entities.Recovery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BA");

                    b.Property<decimal?>("BDAmount");

                    b.Property<string>("BDNo");

                    b.Property<string>("BDRequesterName");

                    b.Property<Guid>("BankDraftId");

                    b.Property<DateTime?>("CPCDate");

                    b.Property<string>("ClaimDuration");

                    b.Property<string>("CoCode");

                    b.Property<DateTime?>("CompletedOn");

                    b.Property<string>("CreatedById");

                    b.Property<string>("CreatedByName");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime?>("DraftedOn");

                    b.Property<string>("ERMSDocNo");

                    b.Property<string>("ErmsDocNo1");

                    b.Property<string>("ErmsDocNo2");

                    b.Property<DateTime?>("FinalPartialSubmissionOn");

                    b.Property<DateTime?>("FinalSubmissionOn");

                    b.Property<decimal?>("FirstRecoveryAmount");

                    b.Property<string>("NameOnBD");

                    b.Property<string>("PBTEmailAddress");

                    b.Property<DateTime?>("PartialCompletedOn");

                    b.Property<DateTime?>("PartialReceivedDate");

                    b.Property<DateTime?>("PartialReceivedOn");

                    b.Property<DateTime?>("PartialSubmittedOn");

                    b.Property<string>("PartialSubmitterId");

                    b.Property<DateTime?>("ProcessedOn");

                    b.Property<string>("ProcesserId");

                    b.Property<string>("ProjNo");

                    b.Property<DateTime?>("ProjectCompletionDate");

                    b.Property<DateTime?>("ReceivedDate");

                    b.Property<DateTime?>("ReceivedOn");

                    b.Property<string>("RecoveryType");

                    b.Property<string>("RefNo");

                    b.Property<string>("RequesterFinalSubmissionComment");

                    b.Property<string>("RequesterId");

                    b.Property<string>("RequesterProcessComment");

                    b.Property<string>("RequesterSubmissionComment");

                    b.Property<decimal?>("SecondRecoveryAmount");

                    b.Property<DateTime?>("SiteVisitDate");

                    b.Property<string>("Stage");

                    b.Property<string>("Status");

                    b.Property<DateTime?>("SubmittedOn");

                    b.Property<string>("SubmitterId");

                    b.Property<string>("TGBSConfirmationComment");

                    b.Property<string>("TGBSPartialReceiverId");

                    b.Property<string>("TGBSPartialValidatorId");

                    b.Property<string>("TGBSReceiverId");

                    b.Property<string>("TGBSValidatorId");

                    b.Property<decimal?>("TotalRecoveryAmount");

                    b.Property<DateTime>("UpdatedOn");

                    b.Property<DateTime?>("WithdrewOn");

                    b.Property<bool>("isActive");

                    b.HasKey("Id");

                    b.HasIndex("BankDraftId");

                    b.HasIndex("RequesterId");

                    b.ToTable("Recovery");
                });

            modelBuilder.Entity("BDA.Entities.RunningNo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Name");

                    b.Property<int>("RunNo");

                    b.Property<DateTime>("UpdatedOn");

                    b.Property<bool>("isActive");

                    b.HasKey("Id");

                    b.ToTable("RunningNo");
                });

            modelBuilder.Entity("BDA.Entities.SendMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("SendMethod");
                });

            modelBuilder.Entity("BDA.Entities.State", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("State");
                });

            modelBuilder.Entity("BDA.Entities.StateMonthlyAmount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal?>("Amount");

                    b.Property<int>("BDNoIssued");

                    b.Property<int>("BDNoOutstanding");

                    b.Property<int>("BDNoRecovered");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<int>("Month");

                    b.Property<decimal?>("OutstandingAmount");

                    b.Property<decimal?>("RecoveryAmount");

                    b.Property<Guid>("StateId");

                    b.Property<DateTime>("UpdatedOn");

                    b.Property<int>("Year");

                    b.Property<bool>("isActive");

                    b.HasKey("Id");

                    b.ToTable("StateMonthlyAmount");
                });

            modelBuilder.Entity("BDA.Entities.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Name");

                    b.Property<DateTime>("UpdatedOn");

                    b.Property<Guid>("ZoneId");

                    b.Property<bool>("isActive");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId");

                    b.ToTable("Unit");
                });

            modelBuilder.Entity("BDA.Entities.VendorNo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("VendorNo");
                });

            modelBuilder.Entity("BDA.Entities.WangCagaran", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Alamat1");

                    b.Property<string>("Alamat2");

                    b.Property<string>("Assignment");

                    b.Property<string>("Bandar");

                    b.Property<Guid>("BankDraftId");

                    b.Property<string>("BusinessArea");

                    b.Property<string>("CajKod");

                    b.Property<string>("CoCode");

                    b.Property<string>("CostCenter");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("ErmsDocNo");

                    b.Property<string>("GL");

                    b.Property<bool?>("JKRInvolved");

                    b.Property<string>("JKRType");

                    b.Property<decimal?>("Jumlah")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("KeteranganKerja");

                    b.Property<string>("NamaPemegangCagaran");

                    b.Property<string>("Negeri");

                    b.Property<string>("PK");

                    b.Property<string>("Pemula");

                    b.Property<string>("Poskod");

                    b.Property<DateTime?>("PostingDate");

                    b.Property<DateTime?>("Tarikh");

                    b.Property<string>("Type");

                    b.Property<DateTime>("UpdatedOn");

                    b.Property<string>("WBSProjekNo");

                    b.Property<bool>("isActive");

                    b.HasKey("Id");

                    b.HasIndex("BankDraftId");

                    b.ToTable("WangCagaran");
                });

            modelBuilder.Entity("BDA.Entities.WangCagaranAttachment", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<Guid?>("AttachmentId");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Type");

                    b.Property<DateTime>("UpdatedOn");

                    b.Property<Guid>("WangCagaranId");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentId");

                    b.HasIndex("WangCagaranId");

                    b.ToTable("WangCagaranAttachment");
                });

            modelBuilder.Entity("BDA.Entities.WangHangus", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BankAccount");

                    b.Property<string>("BankCountry");

                    b.Property<Guid>("BankDraftId");

                    b.Property<string>("BusRegNo");

                    b.Property<string>("BusinessArea");

                    b.Property<string>("City");

                    b.Property<string>("CoCode");

                    b.Property<string>("Country");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description");

                    b.Property<string>("Email");

                    b.Property<string>("ErmsDocNo");

                    b.Property<string>("ICNo");

                    b.Property<string>("InvoiceNumber");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Name");

                    b.Property<string>("PONumber");

                    b.Property<string>("Postcode");

                    b.Property<string>("Region");

                    b.Property<string>("SSTRegNo");

                    b.Property<string>("Street");

                    b.Property<decimal?>("TaxAmount");

                    b.Property<string>("Type");

                    b.Property<DateTime>("UpdatedOn");

                    b.Property<string>("VendorName");

                    b.Property<string>("VendorNo");

                    b.Property<string>("VendorType");

                    b.HasKey("Id");

                    b.HasIndex("BankDraftId");

                    b.ToTable("WangHangus");
                });

            modelBuilder.Entity("BDA.Entities.Zone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<Guid>("FunctionId");

                    b.Property<string>("Name");

                    b.Property<DateTime>("UpdatedOn");

                    b.Property<bool>("isActive");

                    b.HasKey("Id");

                    b.HasIndex("FunctionId");

                    b.ToTable("Zone");
                });

            modelBuilder.Entity("BDA.Identity.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<int>("LOAType");

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<bool>("NeedDivision");

                    b.Property<bool>("NeedFunction");

                    b.Property<bool>("NeedUnit");

                    b.Property<bool>("NeedZone");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.Property<bool>("isActive");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("BDA.Identity.ApplicationRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("BDA.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<int>("AuthenticationMethod");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Designation");

                    b.Property<string>("Division");

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FullName");

                    b.Property<bool>("IsActive");

                    b.Property<DateTime>("LastLogin");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("OfficeNo");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("Unit");

                    b.Property<DateTime>("UpdatedOn");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("BDA.Identity.ApplicationUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("BDA.Identity.ApplicationUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("BDA.Identity.ApplicationUserRole", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.Property<Guid?>("DivisionId");

                    b.Property<Guid?>("FunctionId");

                    b.Property<Guid>("Id");

                    b.Property<Guid?>("UnitId");

                    b.Property<Guid?>("ZoneId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("DivisionId");

                    b.HasIndex("FunctionId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UnitId");

                    b.HasIndex("ZoneId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("BDA.Identity.ApplicationUserToken", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasMaxLength(128);

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("BDA.Entities.AccountingTable", b =>
                {
                    b.HasOne("BDA.Entities.WangHangus", "WangHangus")
                        .WithMany("AccountingTable")
                        .HasForeignKey("WangHangusId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BDA.Entities.BankDraft", b =>
                {
                    b.HasOne("BDA.Identity.ApplicationUser", "Approver")
                        .WithMany()
                        .HasForeignKey("ApproverId");

                    b.HasOne("BDA.Identity.ApplicationUser", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId");

                    b.HasOne("BDA.Identity.ApplicationUser", "TGBSAcceptance")
                        .WithMany()
                        .HasForeignKey("TGBSAcceptanceId");

                    b.HasOne("BDA.Identity.ApplicationUser", "TGBSIssuer")
                        .WithMany()
                        .HasForeignKey("TGBSIssuerId");

                    b.HasOne("BDA.Identity.ApplicationUser", "TGBSProcesser")
                        .WithMany()
                        .HasForeignKey("TGBSProcesserId");

                    b.HasOne("BDA.Identity.ApplicationUser", "Verifier")
                        .WithMany()
                        .HasForeignKey("VerifierId");
                });

            modelBuilder.Entity("BDA.Entities.BankDraftAction", b =>
                {
                    b.HasOne("BDA.Identity.ApplicationUser", "By")
                        .WithMany()
                        .HasForeignKey("ById");
                });

            modelBuilder.Entity("BDA.Entities.BusinessArea", b =>
                {
                    b.HasOne("BDA.Entities.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BDA.Entities.Cancellation", b =>
                {
                    b.HasOne("BDA.Identity.ApplicationUser", "Approver")
                        .WithMany()
                        .HasForeignKey("ApproverId");

                    b.HasOne("BDA.Entities.BankDraft", "BankDraft")
                        .WithMany()
                        .HasForeignKey("BankDraftId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BDA.Identity.ApplicationUser", "ReconReceiver")
                        .WithMany()
                        .HasForeignKey("ReconReceiverId");

                    b.HasOne("BDA.Identity.ApplicationUser", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId");

                    b.HasOne("BDA.Identity.ApplicationUser", "TGBSAcceptance")
                        .WithMany()
                        .HasForeignKey("TGBSAcceptanceId");

                    b.HasOne("BDA.Identity.ApplicationUser", "TGBSProcesser")
                        .WithMany()
                        .HasForeignKey("TGBSProcesserId");
                });

            modelBuilder.Entity("BDA.Entities.ERMSQueues", b =>
                {
                    b.HasOne("BDA.Entities.BankDraft", "BankDrafId")
                        .WithMany()
                        .HasForeignKey("BankDrafIdId");
                });

            modelBuilder.Entity("BDA.Entities.Function", b =>
                {
                    b.HasOne("BDA.Entities.Division", "Division")
                        .WithMany("Function")
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BDA.Entities.InstructionLetterAttachment", b =>
                {
                    b.HasOne("BDA.Entities.Attachment", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId");

                    b.HasOne("BDA.Entities.InstructionLetter", "InstructionLetter")
                        .WithMany("Attachments")
                        .HasForeignKey("InstructionLetterId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BDA.Entities.Lost", b =>
                {
                    b.HasOne("BDA.Identity.ApplicationUser", "Approver")
                        .WithMany()
                        .HasForeignKey("ApproverId");

                    b.HasOne("BDA.Entities.BankDraft", "BankDraft")
                        .WithMany()
                        .HasForeignKey("BankDraftId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BDA.Identity.ApplicationUser", "ReconReceiver")
                        .WithMany()
                        .HasForeignKey("ReconReceiverId");

                    b.HasOne("BDA.Identity.ApplicationUser", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId");

                    b.HasOne("BDA.Identity.ApplicationUser", "TGBSAcceptance")
                        .WithMany()
                        .HasForeignKey("TGBSAcceptanceId");

                    b.HasOne("BDA.Identity.ApplicationUser", "TGBSProcesser")
                        .WithMany()
                        .HasForeignKey("TGBSProcesserId");
                });

            modelBuilder.Entity("BDA.Entities.MemoAttachment", b =>
                {
                    b.HasOne("BDA.Entities.Attachment", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId");

                    b.HasOne("BDA.Entities.Memo", "Memo")
                        .WithMany("Attachments")
                        .HasForeignKey("MemoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BDA.Entities.Recovery", b =>
                {
                    b.HasOne("BDA.Entities.BankDraft", "BankDraft")
                        .WithMany()
                        .HasForeignKey("BankDraftId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BDA.Identity.ApplicationUser", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId");
                });

            modelBuilder.Entity("BDA.Entities.Unit", b =>
                {
                    b.HasOne("BDA.Entities.Zone", "Zone")
                        .WithMany("Unit")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BDA.Entities.WangCagaran", b =>
                {
                    b.HasOne("BDA.Entities.BankDraft", "BankDraft")
                        .WithMany()
                        .HasForeignKey("BankDraftId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BDA.Entities.WangCagaranAttachment", b =>
                {
                    b.HasOne("BDA.Entities.Attachment", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId");

                    b.HasOne("BDA.Entities.WangCagaran", "WangCagaran")
                        .WithMany()
                        .HasForeignKey("WangCagaranId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BDA.Entities.WangHangus", b =>
                {
                    b.HasOne("BDA.Entities.BankDraft", "BankDraft")
                        .WithMany()
                        .HasForeignKey("BankDraftId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BDA.Entities.Zone", b =>
                {
                    b.HasOne("BDA.Entities.Function", "Function")
                        .WithMany("Zone")
                        .HasForeignKey("FunctionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BDA.Identity.ApplicationRoleClaim", b =>
                {
                    b.HasOne("BDA.Identity.ApplicationRole", "Role")
                        .WithMany("RoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BDA.Identity.ApplicationUserClaim", b =>
                {
                    b.HasOne("BDA.Identity.ApplicationUser", "User")
                        .WithMany("Claims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BDA.Identity.ApplicationUserLogin", b =>
                {
                    b.HasOne("BDA.Identity.ApplicationUser", "User")
                        .WithMany("Logins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BDA.Identity.ApplicationUserRole", b =>
                {
                    b.HasOne("BDA.Entities.Division", "Division")
                        .WithMany()
                        .HasForeignKey("DivisionId");

                    b.HasOne("BDA.Entities.Function", "Function")
                        .WithMany()
                        .HasForeignKey("FunctionId");

                    b.HasOne("BDA.Identity.ApplicationRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BDA.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId");

                    b.HasOne("BDA.Identity.ApplicationUser", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BDA.Entities.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId");
                });

            modelBuilder.Entity("BDA.Identity.ApplicationUserToken", b =>
                {
                    b.HasOne("BDA.Identity.ApplicationUser", "User")
                        .WithMany("Tokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
