//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErmsService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace= "urn:tnb.com.my:BDA:po:ALL:TransactionStatus:00", ConfigurationName="ErmsService.SI_TransactionStatus_Sync_In")]
    public interface SI_TransactionStatus_Sync_In
    {
        //[System.ServiceModel.OperationContractAttribute(Action="http://sap.com/xi/WebService/soap1.1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ErmsService.SI_TransactionStatus_Sync_InResponse> SI_TransactionStatus_Sync_InAsync(ErmsService.SI_TransactionStatus_Sync_InRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace= "urn:tnb.com.my:BDA:po:ALL:TransactionStatus:00")]
    public partial class DT_TransactionStatusRequest
    {
        
        private DT_RequestHeader requestHeaderField;
        
        private DT_TransactionStatusRequestTRANSACTION_STATUS tRANSACTION_STATUSField;
        
        private DT_TransactionStatusRequestItem[] tRANSACTION_OUTPUTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public DT_RequestHeader RequestHeader
        {
            get
            {
                return this.requestHeaderField;
            }
            set
            {
                this.requestHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public DT_TransactionStatusRequestTRANSACTION_STATUS TRANSACTION_STATUS
        {
            get
            {
                return this.tRANSACTION_STATUSField;
            }
            set
            {
                this.tRANSACTION_STATUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DT_TransactionStatusRequestItem[] TRANSACTION_OUTPUT
        {
            get
            {
                return this.tRANSACTION_OUTPUTField;
            }
            set
            {
                this.tRANSACTION_OUTPUTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace= "urn:tnb.com.my:BDA:po:ALL:TransactionStatus:00")]
    public partial class DT_RequestHeader
    {
        
        private string requestIdField;
        
        private string reqTransactionIdField;
        
        private string consumerIdField;
        
        private string reqTimestampField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string RequestId
        {
            get
            {
                return this.requestIdField;
            }
            set
            {
                this.requestIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ReqTransactionId
        {
            get
            {
                return this.reqTransactionIdField;
            }
            set
            {
                this.reqTransactionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ConsumerId
        {
            get
            {
                return this.consumerIdField;
            }
            set
            {
                this.consumerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ReqTimestamp
        {
            get
            {
                return this.reqTimestampField;
            }
            set
            {
                this.reqTimestampField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace= "urn:tnb.com.my:BDA:po:ALL:TransactionStatus:00")]
    public partial class DT_ResponseHeader
    {
        
        private string responseIdField;
        
        private string resTransactionIdField;
        
        private string providerIdField;
        
        private string resTimestampField;
        
        private string resStatusField;
        
        private string msgCodeField;
        
        private string msgDescField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ResponseId
        {
            get
            {
                return this.responseIdField;
            }
            set
            {
                this.responseIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ResTransactionId
        {
            get
            {
                return this.resTransactionIdField;
            }
            set
            {
                this.resTransactionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ProviderId
        {
            get
            {
                return this.providerIdField;
            }
            set
            {
                this.providerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ResTimestamp
        {
            get
            {
                return this.resTimestampField;
            }
            set
            {
                this.resTimestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ResStatus
        {
            get
            {
                return this.resStatusField;
            }
            set
            {
                this.resStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string MsgCode
        {
            get
            {
                return this.msgCodeField;
            }
            set
            {
                this.msgCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string MsgDesc
        {
            get
            {
                return this.msgDescField;
            }
            set
            {
                this.msgDescField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace= "urn:tnb.com.my:BDA:po:ALL:TransactionStatus:00")]
    public partial class DT_TransactionStatusResponse
    {
        
        private DT_ResponseHeader responseHeaderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public DT_ResponseHeader ResponseHeader
        {
            get
            {
                return this.responseHeaderField;
            }
            set
            {
                this.responseHeaderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace= "urn:tnb.com.my:BDA:po:ALL:TransactionStatus:00")]
    public partial class DT_TransactionStatusRequestTRANSACTION_STATUS
    {
        
        private string sTATUSField;
        
        private DT_TransactionStatusRequestTRANSACTION_STATUSMESSAGE[] mESSAGEField;
        
        private string cONSUMER_REF_IDField;
        
        private string cONSUMER_REF_SERVICEField;
        
        private string cLIENT_IDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string STATUS
        {
            get
            {
                return this.sTATUSField;
            }
            set
            {
                this.sTATUSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MESSAGE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public DT_TransactionStatusRequestTRANSACTION_STATUSMESSAGE[] MESSAGE
        {
            get
            {
                return this.mESSAGEField;
            }
            set
            {
                this.mESSAGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string CONSUMER_REF_ID
        {
            get
            {
                return this.cONSUMER_REF_IDField;
            }
            set
            {
                this.cONSUMER_REF_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string CONSUMER_REF_SERVICE
        {
            get
            {
                return this.cONSUMER_REF_SERVICEField;
            }
            set
            {
                this.cONSUMER_REF_SERVICEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string CLIENT_ID
        {
            get
            {
                return this.cLIENT_IDField;
            }
            set
            {
                this.cLIENT_IDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace= "urn:tnb.com.my:BDA:po:ALL:TransactionStatus:00")]
    public partial class DT_TransactionStatusRequestTRANSACTION_STATUSMESSAGE
    {
        
        private string mESSAGE_DESCRIPTIONField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MESSAGE_DESCRIPTION
        {
            get
            {
                return this.mESSAGE_DESCRIPTIONField;
            }
            set
            {
                this.mESSAGE_DESCRIPTIONField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace= "urn:tnb.com.my:BDA:po:ALL:TransactionStatus:00")]
    public partial class DT_TransactionStatusRequestItem
    {
        
        private string oUTPUT_NAMEField;
        
        private string oUTPUT_VALUEField;
        
        private string oUTPUT_VALUE2Field;
        
        private string oUTPUT_VALUE3Field;
        
        private string oUTPUT_VALUE4Field;
        
        private string oUTPUT_VALUE5Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string OUTPUT_NAME
        {
            get
            {
                return this.oUTPUT_NAMEField;
            }
            set
            {
                this.oUTPUT_NAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string OUTPUT_VALUE
        {
            get
            {
                return this.oUTPUT_VALUEField;
            }
            set
            {
                this.oUTPUT_VALUEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string OUTPUT_VALUE2
        {
            get
            {
                return this.oUTPUT_VALUE2Field;
            }
            set
            {
                this.oUTPUT_VALUE2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string OUTPUT_VALUE3
        {
            get
            {
                return this.oUTPUT_VALUE3Field;
            }
            set
            {
                this.oUTPUT_VALUE3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string OUTPUT_VALUE4
        {
            get
            {
                return this.oUTPUT_VALUE4Field;
            }
            set
            {
                this.oUTPUT_VALUE4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string OUTPUT_VALUE5
        {
            get
            {
                return this.oUTPUT_VALUE5Field;
            }
            set
            {
                this.oUTPUT_VALUE5Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_TransactionStatus_Sync_InRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace= "urn:tnb.com.my:BDA:po:ALL:TransactionStatus:00", Order=0)]
        public ErmsService.DT_TransactionStatusRequest MT_TransactionStatusRequest;
        
        public SI_TransactionStatus_Sync_InRequest()
        {
        }
        
        public SI_TransactionStatus_Sync_InRequest(ErmsService.DT_TransactionStatusRequest MT_TransactionStatusRequest)
        {
            this.MT_TransactionStatusRequest = MT_TransactionStatusRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_TransactionStatus_Sync_InResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace= "urn:tnb.com.my:BDA:po:ALL:TransactionStatus:00", Order=0)]
        public ErmsService.DT_TransactionStatusResponse MT_TransactionStatusResponse;
        
        public SI_TransactionStatus_Sync_InResponse()
        {
        }
        
        public SI_TransactionStatus_Sync_InResponse(ErmsService.DT_TransactionStatusResponse MT_TransactionStatusResponse)
        {
            this.MT_TransactionStatusResponse = MT_TransactionStatusResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface SI_TransactionStatus_Sync_InChannel : ErmsService.SI_TransactionStatus_Sync_In, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class SI_TransactionStatus_Sync_InClient : System.ServiceModel.ClientBase<ErmsService.SI_TransactionStatus_Sync_In>, ErmsService.SI_TransactionStatus_Sync_In
    {
        
        public SI_TransactionStatus_Sync_InClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ErmsService.SI_TransactionStatus_Sync_InResponse> ErmsService.SI_TransactionStatus_Sync_In.SI_TransactionStatus_Sync_InAsync(ErmsService.SI_TransactionStatus_Sync_InRequest request)
        {
            return base.Channel.SI_TransactionStatus_Sync_InAsync(request);
        }
        
        public System.Threading.Tasks.Task<ErmsService.SI_TransactionStatus_Sync_InResponse> SI_TransactionStatus_Sync_InAsync(ErmsService.DT_TransactionStatusRequest MT_TransactionStatusRequest)
        {
            ErmsService.SI_TransactionStatus_Sync_InRequest inValue = new ErmsService.SI_TransactionStatus_Sync_InRequest();
            inValue.MT_TransactionStatusRequest = MT_TransactionStatusRequest;
            return ((ErmsService.SI_TransactionStatus_Sync_In)(this)).SI_TransactionStatus_Sync_InAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
