//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDA.SI_VendorInvoiceCreate_Async_Out_Service
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:tnb.com.my:BDA:po:FM:VendorInvoiceCreate:00", ConfigurationName="BDA.SI_VendorInvoiceCreate_Async_Out_Service.SI_VendorInvoiceCreate_Async_Out")]
    public interface SI_VendorInvoiceCreate_Async_Out
    {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://sap.com/xi/WebService/soap1.1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task SI_VendorInvoiceCreate_Async_OutAsync(BDA.SI_VendorInvoiceCreate_Async_Out_Service.SI_VendorInvoiceCreate_Async_Out1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:tnb.com.my:BDA:po:FM:VendorInvoiceCreate:00")]
    public partial class DT_VendorInvoiceCreate
    {
        
        private DT_RequestHeader requestHeaderField;
        
        private DT_VendorInvoiceCreateVendorInvoiceCreateRequest vendorInvoiceCreateRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public DT_RequestHeader RequestHeader
        {
            get
            {
                return this.requestHeaderField;
            }
            set
            {
                this.requestHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public DT_VendorInvoiceCreateVendorInvoiceCreateRequest VendorInvoiceCreateRequest
        {
            get
            {
                return this.vendorInvoiceCreateRequestField;
            }
            set
            {
                this.vendorInvoiceCreateRequestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:tnb.com.my:BDA:po:ALL:TransactionStatus:00")]
    public partial class DT_RequestHeader
    {
        
        private string requestIdField;
        
        private string reqTransactionIdField;
        
        private string consumerIdField;
        
        private string reqTimestampField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string RequestId
        {
            get
            {
                return this.requestIdField;
            }
            set
            {
                this.requestIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ReqTransactionId
        {
            get
            {
                return this.reqTransactionIdField;
            }
            set
            {
                this.reqTransactionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ConsumerId
        {
            get
            {
                return this.consumerIdField;
            }
            set
            {
                this.consumerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ReqTimestamp
        {
            get
            {
                return this.reqTimestampField;
            }
            set
            {
                this.reqTimestampField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:tnb.com.my:BDA:po:FM:VendorInvoiceCreate:00")]
    public partial class DT_VendorInvoiceCreateVendorInvoiceCreateRequest
    {
        
        private DT_VendorInvoiceCreateVendorInvoiceCreateRequestItem[] documentHeaderField;
        
        private DT_VendorInvoiceCreateVendorInvoiceCreateRequestVendorItemDataItem[][] vendorItemsField;
        
        private DT_VendorInvoiceCreateVendorInvoiceCreateRequestGLItemDataItem[][] gLItemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DT_VendorInvoiceCreateVendorInvoiceCreateRequestItem[] DocumentHeader
        {
            get
            {
                return this.documentHeaderField;
            }
            set
            {
                this.documentHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("VendorItemData", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false, NestingLevel=1)]
        public DT_VendorInvoiceCreateVendorInvoiceCreateRequestVendorItemDataItem[][] VendorItems
        {
            get
            {
                return this.vendorItemsField;
            }
            set
            {
                this.vendorItemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("GLItemData", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false, NestingLevel=1)]
        public DT_VendorInvoiceCreateVendorInvoiceCreateRequestGLItemDataItem[][] GLItems
        {
            get
            {
                return this.gLItemsField;
            }
            set
            {
                this.gLItemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:tnb.com.my:BDA:po:FM:VendorInvoiceCreate:00")]
    public partial class DT_VendorInvoiceCreateVendorInvoiceCreateRequestItem
    {
        
        private string attributeNameField;
        
        private string attributeValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string AttributeName
        {
            get
            {
                return this.attributeNameField;
            }
            set
            {
                this.attributeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string AttributeValue
        {
            get
            {
                return this.attributeValueField;
            }
            set
            {
                this.attributeValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:tnb.com.my:BDA:po:FM:VendorInvoiceCreate:00")]
    public partial class DT_VendorInvoiceCreateVendorInvoiceCreateRequestVendorItemDataItem
    {
        
        private string attributeNameField;
        
        private string attributeValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string AttributeName
        {
            get
            {
                return this.attributeNameField;
            }
            set
            {
                this.attributeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string AttributeValue
        {
            get
            {
                return this.attributeValueField;
            }
            set
            {
                this.attributeValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:tnb.com.my:BDA:po:FM:VendorInvoiceCreate:00")]
    public partial class DT_VendorInvoiceCreateVendorInvoiceCreateRequestGLItemDataItem
    {
        
        private string attributeNameField;
        
        private string attributeValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string AttributeName
        {
            get
            {
                return this.attributeNameField;
            }
            set
            {
                this.attributeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string AttributeValue
        {
            get
            {
                return this.attributeValueField;
            }
            set
            {
                this.attributeValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SI_VendorInvoiceCreate_Async_Out1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:tnb.com.my:BDA:po:FM:VendorInvoiceCreate:00", Order=0)]
        public BDA.SI_VendorInvoiceCreate_Async_Out_Service.DT_VendorInvoiceCreate MT_VendorInvoiceCreate;
        
        public SI_VendorInvoiceCreate_Async_Out1()
        {
        }
        
        public SI_VendorInvoiceCreate_Async_Out1(BDA.SI_VendorInvoiceCreate_Async_Out_Service.DT_VendorInvoiceCreate MT_VendorInvoiceCreate)
        {
            this.MT_VendorInvoiceCreate = MT_VendorInvoiceCreate;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface SI_VendorInvoiceCreate_Async_OutChannel : BDA.SI_VendorInvoiceCreate_Async_Out_Service.SI_VendorInvoiceCreate_Async_Out, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class SI_VendorInvoiceCreate_Async_OutClient : System.ServiceModel.ClientBase<BDA.SI_VendorInvoiceCreate_Async_Out_Service.SI_VendorInvoiceCreate_Async_Out>, BDA.SI_VendorInvoiceCreate_Async_Out_Service.SI_VendorInvoiceCreate_Async_Out
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SI_VendorInvoiceCreate_Async_OutClient() : 
                base(SI_VendorInvoiceCreate_Async_OutClient.GetDefaultBinding(), SI_VendorInvoiceCreate_Async_OutClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.SI_VendorInvoiceCreate_Async_Out_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SI_VendorInvoiceCreate_Async_OutClient(EndpointConfiguration endpointConfiguration) : 
                base(SI_VendorInvoiceCreate_Async_OutClient.GetBindingForEndpoint(endpointConfiguration), SI_VendorInvoiceCreate_Async_OutClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SI_VendorInvoiceCreate_Async_OutClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SI_VendorInvoiceCreate_Async_OutClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SI_VendorInvoiceCreate_Async_OutClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SI_VendorInvoiceCreate_Async_OutClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SI_VendorInvoiceCreate_Async_OutClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task BDA.SI_VendorInvoiceCreate_Async_Out_Service.SI_VendorInvoiceCreate_Async_Out.SI_VendorInvoiceCreate_Async_OutAsync(BDA.SI_VendorInvoiceCreate_Async_Out_Service.SI_VendorInvoiceCreate_Async_Out1 request)
        {
            return base.Channel.SI_VendorInvoiceCreate_Async_OutAsync(request);
        }
        
        public System.Threading.Tasks.Task SI_VendorInvoiceCreate_Async_OutAsync(BDA.SI_VendorInvoiceCreate_Async_Out_Service.DT_VendorInvoiceCreate MT_VendorInvoiceCreate)
        {
            BDA.SI_VendorInvoiceCreate_Async_Out_Service.SI_VendorInvoiceCreate_Async_Out1 inValue = new BDA.SI_VendorInvoiceCreate_Async_Out_Service.SI_VendorInvoiceCreate_Async_Out1();
            inValue.MT_VendorInvoiceCreate = MT_VendorInvoiceCreate;
            return ((BDA.SI_VendorInvoiceCreate_Async_Out_Service.SI_VendorInvoiceCreate_Async_Out)(this)).SI_VendorInvoiceCreate_Async_OutAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SI_VendorInvoiceCreate_Async_Out_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SI_VendorInvoiceCreate_Async_Out_Port))
            {
                return new System.ServiceModel.EndpointAddress("file:///");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SI_VendorInvoiceCreate_Async_OutClient.GetBindingForEndpoint(EndpointConfiguration.SI_VendorInvoiceCreate_Async_Out_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SI_VendorInvoiceCreate_Async_OutClient.GetEndpointAddress(EndpointConfiguration.SI_VendorInvoiceCreate_Async_Out_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            SI_VendorInvoiceCreate_Async_Out_Port,
        }
    }
}
